spring:
  application:
    name: "green_schedule"
  datasource:
    url: jdbc:postgresql://localhost:5432/green_schedule
    username: useruser
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Security override for testing without new password each startup
  security:
    user:
      name: user
      password: "123456"
server:
  port: 8080